In [3]:
import numpy as np

In [4]:
np.__version__

'2.3.5'

In [5]:
print(type(np.__version__))

<class 'str'>


In [6]:
python_list = [1,2,3,'string',6.7]

numslist =[x for x in range(10)]
numslist


[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [7]:
python_list = [1,2,3,'string',6,7]

In [8]:
# list comprehension [range of an object]
list_comprehensions = [x for x in range (10)]
print(list_comprehensions)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]


In [9]:
print(list_comprehensions*3)
print(type(list_comprehensions))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
<class 'list'>


In [10]:
# in method u pass argument
arr1 = np.array([1,2,3,4,5])
print(arr1)
print(type(arr1))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [11]:
print(arr1*3)
print(type(arr1))

[ 3  6  9 12 15]
<class 'numpy.ndarray'>


In [12]:
#1D Array
arr1d = np.array([1,2,3])
print(arr1d,'\n',arr1d.ndim)

[1 2 3] 
 1


In [13]:
#2D Array
arr2d = np.array([[1,2,3],
                  [1,2,3]])
print(arr2d,'\n',arr2d.ndim)

[[1 2 3]
 [1 2 3]] 
 2


In [14]:
#3D Array
# .ndim is 
arr3d = np.array([[[1,2,3],[1,2,3]],[[1,2,3],[1,2,3]]])
print(arr3d,'\n',arr3d.ndim)

[[[1 2 3]
  [1 2 3]]

 [[1 2 3]
  [1 2 3]]] 
 3


In [15]:
# x is an object of numpy array
x = np.array([2,3,4,5])
type(x)


numpy.ndarray

In [16]:
# ndim - no of dimension
# works on objects, and checks their dimensions
print('Number of dimension arr1d is: ',arr1d.ndim)
print(f'No of dimension arr2d is: {arr2d.ndim}')

Number of dimension arr1d is:  1
No of dimension arr2d is: 2


In [17]:
# using np.shape method, for checking the dimensions of an array
print('Dimension are :',np.shape(arr1d))
print('Dimension are :',np.shape(arr2d))
print('Dimension are :',np.shape(arr3d))

Dimension are : (3,)
Dimension are : (2, 3)
Dimension are : (2, 2, 3)


In [18]:
#
shape1d = arr1d.ndim
shape1d

1

In [19]:
size1d = arr1d.size
size1d

3

In [20]:
arr1d.dtype

dtype('int64')

In [21]:
type(arr1d)

numpy.ndarray

In [22]:
# to find the number of item
arr2d.size


6

In [23]:
#to find the shape of array
arr3d.shape

(2, 2, 3)

In [24]:
# to find dimension
arr3d.ndim

3

In [25]:
#broadcasting

arr1d*30


array([30, 60, 90])

In [26]:
arr1d+arr1d

array([2, 4, 6])

In [27]:
#to use operation must same size
arr1 =np.array([1,2,3,4,5])
print(arr1)

arr2 = np.array([10,20,30,2,4])
print(arr2)

print('result: ',arr1 - arr2)

[1 2 3 4 5]
[10 20 30  2  4]
result:  [ -9 -18 -27   2   1]


In [28]:
a = 10
b = 3

print(a + b) # Addition: 13
print(a - b) # Subtraction: 7
print(a * b) # Multiplication: 30
print(a / b) # Division: 3.333
print(a // b) # Floor division: 3
print(a % b) # Modulus: 1 / remainder
print(a ** b) # Exponental: 1000

13
7
30
3.3333333333333335
3
1
1000


In [29]:
nums = [x for x in range(0,101,2)]
print(nums)

[0, 2, 4, 6, 8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66, 68, 70, 72, 74, 76, 78, 80, 82, 84, 86, 88, 90, 92, 94, 96, 98, 100]


In [30]:
nums1 = nums[:10]
print(nums1)

[0, 2, 4, 6, 8, 10, 12, 14, 16, 18]


In [31]:
# can pass list to array method
arraynums = np.array(nums)
print(arraynums)

[  0   2   4   6   8  10  12  14  16  18  20  22  24  26  28  30  32  34
  36  38  40  42  44  46  48  50  52  54  56  58  60  62  64  66  68  70
  72  74  76  78  80  82  84  86  88  90  92  94  96  98 100]


In [32]:
# [first value: end value: space]
print(arraynums[10:40:5])

[20 30 40 50 60 70]


In [33]:
print(arraynums[90:40:-5])

[100  90]


In [34]:
# linspace - values are evenly spaced and stored in array
# From 0 to 1, divide by 5 evenly
line = np.linspace(0,1,5)
line

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [35]:
# take in tuples of shape and return arrays
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [36]:
# take in tuples of shape and return arrays
np.ones((4,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [37]:
# random numbers
randomArray = np.random.rand(3,4)
randomArray

array([[0.17831305, 0.90762121, 0.85779607, 0.91990862],
       [0.36085038, 0.55532794, 0.30714951, 0.30945452],
       [0.30302677, 0.06489801, 0.35014412, 0.32828602]])

In [38]:
# random numbers randint
# start, stop, shape (row*column)
randomArray = np.random.randint(0,100,(2,5))
randomArray

array([[56,  5, 69,  5, 53],
       [86, 79, 98, 57,  5]], dtype=int32)

In [39]:
# random class in numpy
# seed make the random value fix like a page

np.random.seed(1)
# .randint(start,stop,(row,column))
randomSeed = np.random.randint(1,100,(2,3))
randomSeed


array([[38, 13, 73],
       [10, 76,  6]], dtype=int32)

In [40]:
# .rand(no of values)
# .rand(row,column)
# .randint(start,stop)
# .randint(start,stop,(row,column))

randomArray = np.random.rand(40)
print(randomArray,'\n')

randomArray = np.random.rand(2,4)
print(randomArray,'\n')

randomArray = np.random.randint(3,400)
print(randomArray,'\n')

randomArray = np.random.randint(3,400,(2,2,3))
print(randomArray)

[0.14675589 0.09233859 0.18626021 0.34556073 0.39676747 0.53881673
 0.41919451 0.6852195  0.20445225 0.87811744 0.02738759 0.67046751
 0.4173048  0.55868983 0.14038694 0.19810149 0.80074457 0.96826158
 0.31342418 0.69232262 0.87638915 0.89460666 0.08504421 0.03905478
 0.16983042 0.8781425  0.09834683 0.42110763 0.95788953 0.53316528
 0.69187711 0.31551563 0.68650093 0.83462567 0.01828828 0.75014431
 0.98886109 0.74816565 0.28044399 0.78927933] 

[[0.10322601 0.44789353 0.9085955  0.29361415]
 [0.28777534 0.13002857 0.01936696 0.67883553]] 

139 

[[[291 269 282]
  [146 242  90]]

 [[284 246 351]
  [ 77 193 305]]]


In [41]:
flatarray = randomArray.flatten()
flatarray

array([291, 269, 282, 146, 242,  90, 284, 246, 351,  77, 193, 305],
      dtype=int32)

In [42]:
reshapearray = randomArray.reshape(6,2)
reshapearray

array([[291, 269],
       [282, 146],
       [242,  90],
       [284, 246],
       [351,  77],
       [193, 305]], dtype=int32)

In [43]:
# aggregation
data = np.array([85,94,22,68,94,54,98])

#sum
#mean
#min max

print(data.sum())

515


In [44]:
# create a list of 1 to 10
# use list comprehension - [number : expressison]
# give me the addition of numbers from 1 to 10

nums = np.array([x for x in range (1,11)])
print(nums)
print(nums.sum())

[ 1  2  3  4  5  6  7  8  9 10]
55


In [56]:
a_2d_matrix = np.ones([2,4])
a_2d_matrix

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [ ]:
# axis column wise - no of output in each column
a_2d_matrix.sum(axis=0)

array([2., 2., 2., 2.])

In [ ]:
# axis row wise - no of output in each row
a_2d_matrix.sum(axis=1)

array([4., 4.])

In [ ]:
# arange(a) - create a list orderly 0 to 9

range_of_numbers = np.arange(10)
range_of_numbers

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
# .arange(a,b) create a range from 1 to 9
range_of_numbers = np.arange(1,10)
range_of_numbers

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [64]:
# arange and reshape
range_example = np.arange(1,11).reshape(5,2)
range_example

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])