In [66]:
import numpy as np

In [67]:
np.__version__

'2.3.5'

In [68]:
print(type(np.__version__))

<class 'str'>


In [69]:
python_list = [1,2,3,'string',6.7]

numslist =[x for x in range(10)]
numslist


[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [70]:
python_list = [1,2,3,'string',6,7]

In [71]:
# list comprehension [range of an object]
list_comprehensions = [x for x in range (10)]
print(list_comprehensions)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]


In [72]:
print(list_comprehensions*3)
print(type(list_comprehensions))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
<class 'list'>


In [73]:
# in method u pass argument
arr1 = np.array([1,2,3,4,5])
print(arr1)
print(type(arr1))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [74]:
print(arr1*3)
print(type(arr1))

[ 3  6  9 12 15]
<class 'numpy.ndarray'>


In [75]:
#1D Array
arr1d = np.array([1,2,3])
print(arr1d,'\n',arr1d.ndim)

[1 2 3] 
 1


In [76]:
#2D Array
arr2d = np.array([[1,2,3],
                  [1,2,3]])
print(arr2d,'\n',arr2d.ndim)

[[1 2 3]
 [1 2 3]] 
 2


In [77]:
#3D Array
# .ndim is 
arr3d = np.array([[[1,2,3],[1,2,3]],[[1,2,3],[1,2,3]]])
print(arr3d,'\n',arr3d.ndim)

[[[1 2 3]
  [1 2 3]]

 [[1 2 3]
  [1 2 3]]] 
 3


In [78]:
# x is an object of numpy array
x = np.array([2,3,4,5])
type(x)


numpy.ndarray

In [79]:
# ndim - no of dimension
# works on objects, and checks their dimensions
print('Number of dimension arr1d is: ',arr1d.ndim)
print(f'No of dimension arr2d is: {arr2d.ndim}')

Number of dimension arr1d is:  1
No of dimension arr2d is: 2


In [82]:
# using np.shape method, for checking the dimensions of an array
print('Dimension are :',np.shape(arr1d))
print('Dimension are :',np.shape(arr2d))
print('Dimension are :',np.shape(arr3d))

Dimension are : (3,)
Dimension are : (2, 3)
Dimension are : (2, 2, 3)


In [91]:
#
shape1d = arr1d.ndim
shape1d

1

In [90]:
size1d = arr1d.size
size1d

3

In [92]:
arr1d.dtype

dtype('int64')

In [93]:
type(arr1d)

numpy.ndarray

In [ ]:
# to find the number of item
arr2d.size


6

In [104]:
#to find the shape of array
arr3d.shape

(2, 2, 3)

In [ ]:
# to find dimension
arr3d.ndim

3

In [111]:
#broadcasting

arr1d*30


array([30, 60, 90])

In [109]:
arr1d+arr1d

array([2, 4, 6])

In [ ]:
#to use operation must same size
arr1 =np.array([1,2,3,4,5])
print(arr1)

arr2 = np.array([10,20,30,2,4])
print(arr2)

print('result: ',arr1 - arr2)

[1 2 3 4 5]
[10 20 30  2  4]
result:  [ -9 -18 -27   2   1]


In [126]:
a = 10
b = 3

print(a + b) # Addition: 13
print(a - b) # Subtraction: 7
print(a * b) # Multiplication: 30
print(a / b) # Division: 3.333
print(a // b) # Floor division: 3
print(a % b) # Modulus: 1 / remainder
print(a ** b) # Exponental: 1000

13
7
30
3.3333333333333335
3
1
1000


In [127]:
nums = [x for x in range(0,101,2)]
print(nums)

[0, 2, 4, 6, 8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66, 68, 70, 72, 74, 76, 78, 80, 82, 84, 86, 88, 90, 92, 94, 96, 98, 100]


In [132]:
nums1 = nums[:10]
print(nums1)

[0, 2, 4, 6, 8, 10, 12, 14, 16, 18]


In [139]:
# can pass list to array method
arraynums = np.array(nums)
print(arraynums)

[  0   2   4   6   8  10  12  14  16  18  20  22  24  26  28  30  32  34
  36  38  40  42  44  46  48  50  52  54  56  58  60  62  64  66  68  70
  72  74  76  78  80  82  84  86  88  90  92  94  96  98 100]


In [ ]:
# [first value: end value: space]
print(arraynums[10:40:5])

[20 30 40 50 60 70]


In [143]:
print(arraynums[90:40:-5])

[100  90]


In [146]:
# linspace - values are evenly spaced and stored in array
# From 0 to 1, divide by 5 evenly
line = np.linspace(0,1,5)
line

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [149]:
# take in tuples of shape and return arrays
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [150]:
# take in tuples of shape and return arrays
np.ones((4,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [154]:
# random numbers
randomArray = np.random.rand(3,4)
randomArray

array([[0.82107594, 0.94422638, 0.36277778, 0.33080165],
       [0.22112949, 0.84686439, 0.3434485 , 0.67658482],
       [0.73878519, 0.1609729 , 0.56801567, 0.1844412 ]])

In [163]:
# random numbers randint
# start, stop, shape (row*column)
randomArray = np.random.randint(0,100,(2,5))
randomArray

array([[59, 90, 86, 94, 71],
       [54, 37, 82, 41, 38]], dtype=int32)

In [192]:
# random class in numpy
# seed make the random value fix like a page

np.random.seed(1)
# .randint(start,stop,(row,column))
randomSeed = np.random.randint(1,100,(2,3))
randomSeed


array([[38, 13, 73],
       [10, 76,  6]], dtype=int32)

In [206]:
# .rand(no of values)
# .rand(row,column)
# .randint(start,stop)
# .randint(start,stop,(row,column))

randomArray = np.random.rand(40)
print(randomArray,'\n')

randomArray = np.random.rand(2,4)
print(randomArray,'\n')

randomArray = np.random.randint(3,400)
print(randomArray,'\n')

randomArray = np.random.randint(3,400,(2,2,3))
print(randomArray)

[0.85988358 0.18511431 0.08354635 0.0442723  0.44380799 0.01931875
 0.06703205 0.81177151 0.63629061 0.77285043 0.70568214 0.23821092
 0.04441794 0.2812169  0.86508964 0.07312331 0.66033189 0.18737858
 0.52228657 0.90387927 0.47515273 0.84702228 0.83877941 0.13928005
 0.54030456 0.46708531 0.2186829  0.44082832 0.48027818 0.33328431
 0.00891268 0.50546393 0.67314728 0.05545932 0.15757963 0.60510323
 0.31922379 0.89051712 0.79037352 0.21749922] 

[[0.200209   0.68044006 0.15621683 0.51036099]
 [0.98806468 0.1446919  0.04830001 0.899064  ]] 

238 

[[[102 303 283]
  [338  24 336]]

 [[ 36   7  42]
  [127  70 165]]]


In [210]:
flatarray = randomArray.flatten()
flatarray

array([102, 303, 283, 338,  24, 336,  36,   7,  42, 127,  70, 165],
      dtype=int32)

In [213]:
reshapearray = randomArray.reshape(6,2)
reshapearray

array([[102, 303],
       [283, 338],
       [ 24, 336],
       [ 36,   7],
       [ 42, 127],
       [ 70, 165]], dtype=int32)

In [233]:
# aggregation
data = np.array([85,94,22,68,94,54,98])

#sum
#mean
#min max

print(data.sum())

515


In [234]:
# create a list of 1 to 10
# use list comprehension - [number : expressison]
# give me the addition of numbers from 1 to 10

nums = np.array([x for x in range (1,11)])
print(nums)
print(nums.sum())

[ 1  2  3  4  5  6  7  8  9 10]
55
