In [1]:
import numpy as np

In [2]:
a = np.array([10,20,30])

In [11]:
b = np.array([[1,2.2],[3.2,4]])

In [16]:
# dtype - data type of array int/float etc
print(a.dtype)
# type - python function (class of the object)
type(a)

int64


numpy.ndarray

In [22]:
print(a[1])
print(b[0,1])
print(b[1,1])

20
2.2
4.0


In [27]:
# Slicing :
b[1:2]

array([[3.2, 4. ]])

In [28]:
b[:]

array([[1. , 2.2],
       [3.2, 4. ]])

In [29]:
b[0:]

array([[1. , 2.2],
       [3.2, 4. ]])

In [30]:
b[3:]

array([], shape=(0, 2), dtype=float64)

In [31]:
b[:3]

array([[1. , 2.2],
       [3.2, 4. ]])

In [35]:
b[0]

array([1. , 2.2])

In [43]:
c = np.array([[1,2,0,0],[1,2,3,4],[5,6,7,8]])
print(c)
c[0:2, 1:3]
# Rows 0-1, column 1-2

[[1 2 0 0]
 [1 2 3 4]
 [5 6 7 8]]


array([[2, 0],
       [2, 3]])

In [44]:
# Select whole row or whole column

c

array([[1, 2, 0, 0],
       [1, 2, 3, 4],
       [5, 6, 7, 8]])

In [48]:
# select row arr[x] or arr[x, :]
print(c[1])
# or
c[1, :]


[1 2 3 4]


array([1, 2, 3, 4])

In [49]:
# select column arr[:,x]
c[:,2]

array([0, 3, 7])