In [59]:
import numpy as np

A = np.array(
[[2,3,4],
[6,7,8],
[3,2,3]]
)

B = np.array(
[[3,3,3],
[3,3,3],
[3,3,3]]
)


In [60]:
multiply = B @ A
print(multiply)
# Cannot print A @ B coz different dimension

[[33 36 45]
 [33 36 45]
 [33 36 45]]


In [61]:
# @ multiply like matrices while, * times each value
print('\nMatrix Multiplication: \n',A @ B)
print('\nSimple Array Multiplication: \n',A * B)

print('\nMatrix Multiplication: \n',B @ A)
print('\nSimple Array Multiplication: \n',B * A)


Matrix Multiplication: 
 [[27 27 27]
 [63 63 63]
 [24 24 24]]

Simple Array Multiplication: 
 [[ 6  9 12]
 [18 21 24]
 [ 9  6  9]]

Matrix Multiplication: 
 [[33 36 45]
 [33 36 45]
 [33 36 45]]

Simple Array Multiplication: 
 [[ 6  9 12]
 [18 21 24]
 [ 9  6  9]]


In [15]:
A = np.array(
    [[5,5,5],
     [18,18,18],
     [45,45,45]]
)
B = np.array(
    [[15,15,15],
     [6,6,6],
     [1,2,1]]
)

In [44]:
# np.zeros (row x col)
np.zeros((3,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [45]:
np.ones((2,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [ ]:
#np.arange(start,stop,step)
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [46]:
# np.linspace(start,stop,even spaced between)
np.linspace(0,1,5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [52]:
import numpy as np

In [64]:
arr = np.array([[1,2,3],[4,5,6]])
print(arr.shape)
print(arr.dtype)


(2, 3)
int64


In [ ]:
# pow(value, power)
import math
math.pow(5,3) 

125.0